package notification

const (
	SENDING_MONEY = iota
	RECEVIEING_MONEY
	DEPOSIT
	WITHDRAW
)

const (
	SUCESSFUL_PAYMENT             = 0
	INSUFFIECENT_BALANCE          = 1
	USER_IS_NONEEXISTANT          = 2001
	USER_REJECTED_PAYMENT         = 1031
	USER_STILL_REJECTED           = 1032
	USER_COULD_NOT_BE_LOCATED     = 1037
	THE_OPERATOR_IS_NONE_EXISTANT = "SFC_IC0003"
)
